server:
  port: 9998
datasource:
  dirverName: mysql
  host: 127.0.0.1
  port: 3306
  database: labelproject
  username: root
  password: Xz19990817.
  charset: utf8
redis:
  host: 127.0.0.1
  port: 6379