version: '3.3'
services: 
  db: 
    container_name: mysql
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      extnetwork-java:
        ipv4_address: 172.20.0.2
    volumes: 
      - "/home/xingzheng/data/mysql2/data:/var/lib/mysql:rw"
    ports: 
      - 3306:3306

  cache:
    container_name: redis
    image: redis:3.2
    command: redis-server
    networks:
      extnetwork-java:
        ipv4_address: 172.20.0.3
  web:
    container_name: labelproject-back-test
    image: labelproject-back:test
    networks:
      extnetwork-java:
        ipv4_address: 172.20.0.4
    volumes: 
      - "/home/xingzheng/data/labelproject2/home:/home"
    ports: 
      - 8887:8887
    links:
      - cache:redis
      - db:mysql

  web-fore:
    container_name: labelproject-fore-jave
    image: labelproject-foreground-java:test
    networks:
      extnetwork-java:
        ipv4_address: 172.20.0.6
    ports: 
      - 8889:80


networks:
   extnetwork-java:
      ipam:
         config:
         - subnet: 172.20.0.0/16
